# Generated by Django 3.1.5 on 2021-03-13 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['step_num']},
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('recipe', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('recipe', 'step_num')},
        ),
    ]
