# Generated by Django 3.1.5 on 2021-03-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210313_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='step_num',
            field=models.IntegerField(),
        ),
    ]
